# Site settings
title: Orion Blog
SEOTitle: Oz的博客 | Orion Blog
header-img: img/home-bg.jpg
email: europe.lee@gmail.com
description: "software engineer, technology greed, history hobbyist#知行合一，小确幸"
keyword: "orion, oz, europe, blog, programming, technology"
url: "http://athenacloud.net"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     europeli
github_username:    europelee
#linkedin_username:  firstname-lastname-idxxxx
ba_track_id: a599edec407c3e2764b8c3d5e1324073


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: false                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "live fun, enjoy life"
sidebar-avatar: /img/avatar-oz-sz.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Links
links: [
    {
        title: "google",
        href: "https://www.google.com"
    },
    {
        title: "infoq-cn",
        href: "https://www.infoq.cn"
    },
    {
        title: "devdocs",
        href: "https://devdocs.io"
    },
    {
        title: "awesome",
        href: "https://github.com/sindresorhus/awesome"
    }
]

# theme: jekyll-theme-time-machine
